server:
  port: 7070

spring:
  datasource:
    url: jdbc:h2:file:./data/trendsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  newsapi:
    apiKey: <apikey>          # free at newsapi.org
    baseUrl: https://newsapi.org/v2
    pageSize: 10                           # articles to fetch per category
    language: en
    categories: technology,business,science,health,general

  article:
    maxPerFeed: 10
    minContentLength: 150                  # skip articles with less than 150 chars

  ranking:
    topTopics: 3

  video:
    outputDir: C:/Sham/trending_video_generator/video-output
    workspaceDir: C:/Sham/trending_video_generator/video-workspace
    ffmpegPath: C:/Sham/trending_video_generator/ffmpeg/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe

  portal:
    uploadUrl: http://localhost:7070/api/trends-video/test
    apiKey: demo-api-key

#  groq:
#    baseUrl: https://api.groq.com/openai/v1
#    model: llama3-70b-8192                 # fast, reliable, free tier

  ollama:
    baseUrl: http://localhost:11434
    model: llama3.2:1b
    timeoutSeconds: 120                    # fallback if Groq fails

  unsplash:
    accessKey: <accesskey>

  edgetts:
    voice: en-US-AriaNeural
    rate: "+0%"
    volume: "+0%"
    executablePath: C:/Users/shama/AppData/Local/Programs/Python/Python310/Scripts/edge-tts.exe

logging:
  level:
    com.agent.video.generator: INFO
